# Generated by Django 3.2 on 2021-04-11 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_post_name_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
