# Generated by Django 3.2 on 2021-04-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_post_name_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-creation',)},
        ),
    ]
