# Generated by Django 3.2 on 2021-04-12 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
